project:
  type: book
  output-dir: _book/html

book:
  title: "Quantitative Reasoning"
  subtitle: "A Rigorous Alternative for Algebra 2"
  author: "Hawaii QR Workgroup"
  favicon: "images/favicon-32x32.png"
  twitter-card: true

  sidebar:
    logo: "images/DOE-logo.png"
    collapse-level: 1

  chapters:
    - index.qmd
    - chapters/numbers/index.qmd
    - chapters/space/index.qmd
    - chapters/data/index.qmd
    - chapters/patterns/index.qmd
    - chapters/uncertainty/index.qmd
    - chapters/finances/index.qmd
    - references.qmd

crossref:
  fig-prefix: "Figure"
  chapters: true  # <--- Forces Chapter.Figure numbering (e.g., 2.1, 2.2) in PDF/Typst

bibliography: references.bib

format:
  html:
    theme: cosmo
  typst:
    toc: true
    citeproc: true
    number-sections: true
    number-depth: 3
    section-numbering: "1.1"
    template-partials:
      - style/typst-template.typ
      - style/typst-show.typ