name: Render and Deploy Quarto Project

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # Set up Python without demanding a requirements file
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Install Python dependencies only if requirements.txt exists
      - name: Install Python Dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Render Quarto Project
        run: quarto render --to html

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _book/html   # Make sure this matches output-dir in _quarto.yml

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4